"""make custodian fields optional

Revision ID: 1660f5fc6c18
Revises: 61bf62efc1c7
Create Date: 2026-02-23 16:43:49.392291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1660f5fc6c18'
down_revision: Union[str, None] = '61bf62efc1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
