"""Add approval_status to schools and bece_schools

Revision ID: 1e67131b08f7
Revises: d0f14ca8f76e
Create Date: 2026-03-02 17:49:45.545144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e67131b08f7'
down_revision: Union[str, None] = 'd0f14ca8f76e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bece_schools', sa.Column('approval_status', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('approval_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'approval_status')
    op.drop_column('bece_schools', 'approval_status')
    # ### end Alembic commands ###
