"""add school email

Revision ID: 21aa22ec0437
Revises: 1624632fd867
Create Date: 2026-02-21 06:02:35.219091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21aa22ec0437'
down_revision: Union[str, None] = '1624632fd867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('email', sa.String(), nullable=True))
    op.add_column('states', sa.Column('email', sa.String(), nullable=True))
    op.add_column('states', sa.Column('is_locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'is_locked')
    op.drop_column('states', 'email')
    op.drop_column('schools', 'email')
    # ### end Alembic commands ###
