"""add school accreditation

Revision ID: 38779b48e867
Revises: 21aa22ec0437
Create Date: 2026-02-21 06:58:42.312061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38779b48e867'
down_revision: Union[str, None] = '21aa22ec0437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('accreditation_status', sa.String(), server_default='Unaccredited', nullable=True))
    op.add_column('schools', sa.Column('accredited_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'accredited_date')
    op.drop_column('schools', 'accreditation_status')
    # ### end Alembic commands ###
