"""add accreditation_type to schools and bece_schools

Revision ID: 42bd41ea783a
Revises: 728e47e203a8
Create Date: 2026-03-20 19:55:38.074154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42bd41ea783a'
down_revision: Union[str, None] = '728e47e203a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bece_schools', sa.Column('accreditation_type', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('accreditation_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'accreditation_type')
    op.drop_column('bece_schools', 'accreditation_type')
    # ### end Alembic commands ###
