"""add category to schools

Revision ID: 61bf62efc1c7
Revises: d3408cf18135
Create Date: 2026-02-23 16:07:07.104530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bf62efc1c7'
down_revision: Union[str, None] = 'd3408cf18135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bece_schools', sa.Column('category', sa.String(), server_default='PUB', nullable=True))
    op.add_column('schools', sa.Column('category', sa.String(), server_default='PUB', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'category')
    op.drop_column('bece_schools', 'category')
    # ### end Alembic commands ###
