"""add ministry_email to states table

Revision ID: 728e47e203a8
Revises: c8a1d2e3f4b5
Create Date: 2026-03-20 14:34:24.447641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728e47e203a8'
down_revision: Union[str, None] = 'c8a1d2e3f4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('ministry_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'ministry_email')
    # ### end Alembic commands ###
