"""make custodian fields optional

Revision ID: 988cd45a8a03
Revises: 1660f5fc6c18
Create Date: 2026-02-23 16:44:32.838645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '988cd45a8a03'
down_revision: Union[str, None] = '1660f5fc6c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
