"""add_payment_url_to_schools

Revision ID: b410ec73d673
Revises: 58ae05d9bbdd
Create Date: 2026-02-25 20:29:34.324712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b410ec73d673'
down_revision: Union[str, None] = '58ae05d9bbdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bece_schools', sa.Column('payment_url', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('payment_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'payment_url')
    op.drop_column('bece_schools', 'payment_url')
    # ### end Alembic commands ###
