"""add zone email and user zone code

Revision ID: c27c66715bdb
Revises: 53fb61be2cad
Create Date: 2026-05-02 20:12:01.163096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27c66715bdb'
down_revision: Union[str, None] = '53fb61be2cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zone_code', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'zones', ['zone_code'], ['code'])
    op.add_column('zones', sa.Column('zone_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'zone_email')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'zone_code')
    # ### end Alembic commands ###
