"""Add bece_custodian table and update bece_schools link

Revision ID: d0f14ca8f76e
Revises: a7b2c3d4e5f6
Create Date: 2026-03-02 14:35:29.696303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f14ca8f76e'
down_revision: Union[str, None] = 'a7b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bece_custodians',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('state_code', sa.String(), nullable=True),
    sa.Column('lga_code', sa.String(), nullable=True),
    sa.Column('town', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=True),
    sa.ForeignKeyConstraint(['lga_code'], ['lgas.code'], ),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_bece_custodians_code'), 'bece_custodians', ['code'], unique=False)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_constraint(op.f('bece_schools_custodian_code_fkey'), 'bece_schools', type_='foreignkey')
    op.create_foreign_key(None, 'bece_schools', 'bece_custodians', ['custodian_code'], ['code'])
    op.alter_column('lgas', 'state_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lgas', 'state_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'bece_schools', type_='foreignkey')
    op.create_foreign_key(op.f('bece_schools_custodian_code_fkey'), 'bece_schools', 'custodians', ['custodian_code'], ['code'])
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_index(op.f('ix_bece_custodians_code'), table_name='bece_custodians')
    op.drop_table('bece_custodians')
    # ### end Alembic commands ###
