"""add bece schools

Revision ID: d3408cf18135
Revises: 38779b48e867
Create Date: 2026-02-21 10:29:44.643138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3408cf18135'
down_revision: Union[str, None] = '38779b48e867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bece_schools',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('state_code', sa.String(), nullable=True),
    sa.Column('lga_code', sa.String(), nullable=True),
    sa.Column('custodian_code', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('accreditation_status', sa.String(), server_default='Unaccredited', nullable=True),
    sa.Column('accredited_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=True),
    sa.ForeignKeyConstraint(['custodian_code'], ['custodians.code'], ),
    sa.ForeignKeyConstraint(['lga_code'], ['lgas.code'], ),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_bece_schools_code'), 'bece_schools', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bece_schools_code'), table_name='bece_schools')
    op.drop_table('bece_schools')
    # ### end Alembic commands ###
