"""add accrd_year to schools

Revision ID: f3a6cc731679
Revises: 988cd45a8a03
Create Date: 2026-02-23 16:58:53.229400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a6cc731679'
down_revision: Union[str, None] = '988cd45a8a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bece_schools', sa.Column('accrd_year', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('accrd_year', sa.String(), nullable=True))
    op.drop_constraint(op.f('users_state_code_fkey'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_state_code_fkey'), 'users', 'states', ['state_code'], ['code'])
    op.drop_column('schools', 'accrd_year')
    op.drop_column('bece_schools', 'accrd_year')
    # ### end Alembic commands ###
